- name: update yum packages
  yum: list=updates update_cache=true

- name: set Asia/Seoul timezone
  become: yes
  timezone:
    name: Asia/Seoul

- name: install git
  become: yes
  yum:
    name: git
    state: latest

- name: install wget
  become: yes
  yum:
    name: wget
    state: latest

- name: install ruby
  become: yes
  yum:
    name: ruby
    state: latest

- name: remove unused yum packages -ntp
  become: yes
  yum:
    name: ntp
    state: absent
