- name: Add tomcat group
  sudo: yes
  group:
    name: tomcat

- name: Add "tomcat" user
  sudo: yes
  user:
    name: tomcat
    group: tomcat
    home: /service/tomcat
    createhome: no
    system: yes

- name: Create a tomcat directory
  sudo: yes
  file:
    path: /service/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Download Tomcat
  sudo: yes
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"
    owner: tomcat
    group: tomcat

- name: Extract tomcat archive
  sudo: yes
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /service/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /service/tomcat/bin

- name: tomcat bin permission
  sudo: yes
  file:
    path: /service/tomcat/bin
    mode: "0770"
    recurse: yes
